// Code generated by mockery v2.46.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-notes/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGetAllNotesService is an autogenerated mock type for the GetAllNotesService type
type MockGetAllNotesService struct {
	mock.Mock
}

type MockGetAllNotesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetAllNotesService) EXPECT() *MockGetAllNotesService_Expecter {
	return &MockGetAllNotesService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, selector
func (_m *MockGetAllNotesService) Exec(ctx context.Context, selector *models.GetAllNotes) ([]*models.Note, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*models.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetAllNotes) ([]*models.Note, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetAllNotes) []*models.Note); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.GetAllNotes) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetAllNotesService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetAllNotesService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - selector *models.GetAllNotes
func (_e *MockGetAllNotesService_Expecter) Exec(ctx interface{}, selector interface{}) *MockGetAllNotesService_Exec_Call {
	return &MockGetAllNotesService_Exec_Call{Call: _e.mock.On("Exec", ctx, selector)}
}

func (_c *MockGetAllNotesService_Exec_Call) Run(run func(ctx context.Context, selector *models.GetAllNotes)) *MockGetAllNotesService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GetAllNotes))
	})
	return _c
}

func (_c *MockGetAllNotesService_Exec_Call) Return(_a0 []*models.Note, _a1 error) *MockGetAllNotesService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetAllNotesService_Exec_Call) RunAndReturn(run func(context.Context, *models.GetAllNotes) ([]*models.Note, error)) *MockGetAllNotesService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetAllNotesService creates a new instance of MockGetAllNotesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllNotesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllNotesService {
	mock := &MockGetAllNotesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
