// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-notes/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockListNotesService is an autogenerated mock type for the ListNotesService type
type MockListNotesService struct {
	mock.Mock
}

type MockListNotesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListNotesService) EXPECT() *MockListNotesService_Expecter {
	return &MockListNotesService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, selector
func (_m *MockListNotesService) Exec(ctx context.Context, selector *models.ListNotes) ([]*models.Note, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*models.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ListNotes) ([]*models.Note, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.ListNotes) []*models.Note); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.ListNotes) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListNotesService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockListNotesService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - selector *models.ListNotes
func (_e *MockListNotesService_Expecter) Exec(ctx interface{}, selector interface{}) *MockListNotesService_Exec_Call {
	return &MockListNotesService_Exec_Call{Call: _e.mock.On("Exec", ctx, selector)}
}

func (_c *MockListNotesService_Exec_Call) Run(run func(ctx context.Context, selector *models.ListNotes)) *MockListNotesService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ListNotes))
	})
	return _c
}

func (_c *MockListNotesService_Exec_Call) Return(_a0 []*models.Note, _a1 error) *MockListNotesService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListNotesService_Exec_Call) RunAndReturn(run func(context.Context, *models.ListNotes) ([]*models.Note, error)) *MockListNotesService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListNotesService creates a new instance of MockListNotesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListNotesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListNotesService {
	mock := &MockListNotesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
