// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-notes/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGetNoteService is an autogenerated mock type for the GetNoteService type
type MockGetNoteService struct {
	mock.Mock
}

type MockGetNoteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetNoteService) EXPECT() *MockGetNoteService_Expecter {
	return &MockGetNoteService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, selector
func (_m *MockGetNoteService) Exec(ctx context.Context, selector *models.GetNote) (*models.Note, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetNote) (*models.Note, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetNote) *models.Note); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.GetNote) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetNoteService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetNoteService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - selector *models.GetNote
func (_e *MockGetNoteService_Expecter) Exec(ctx interface{}, selector interface{}) *MockGetNoteService_Exec_Call {
	return &MockGetNoteService_Exec_Call{Call: _e.mock.On("Exec", ctx, selector)}
}

func (_c *MockGetNoteService_Exec_Call) Run(run func(ctx context.Context, selector *models.GetNote)) *MockGetNoteService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GetNote))
	})
	return _c
}

func (_c *MockGetNoteService_Exec_Call) Return(_a0 *models.Note, _a1 error) *MockGetNoteService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetNoteService_Exec_Call) RunAndReturn(run func(context.Context, *models.GetNote) (*models.Note, error)) *MockGetNoteService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetNoteService creates a new instance of MockGetNoteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetNoteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetNoteService {
	mock := &MockGetNoteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
