// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-notes/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockListNotesByIDRepository is an autogenerated mock type for the ListNotesByIDRepository type
type MockListNotesByIDRepository struct {
	mock.Mock
}

type MockListNotesByIDRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListNotesByIDRepository) EXPECT() *MockListNotesByIDRepository_Expecter {
	return &MockListNotesByIDRepository_Expecter{mock: &_m.Mock}
}

// GetNoteByID provides a mock function with given fields: ctx, authorID, notesID
func (_m *MockListNotesByIDRepository) GetNoteByID(ctx context.Context, authorID string, notesID []string) ([]*entities.Note, error) {
	ret := _m.Called(ctx, authorID, notesID)

	if len(ret) == 0 {
		panic("no return value specified for GetNoteByID")
	}

	var r0 []*entities.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]*entities.Note, error)); ok {
		return rf(ctx, authorID, notesID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []*entities.Note); ok {
		r0 = rf(ctx, authorID, notesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, authorID, notesID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListNotesByIDRepository_ListNotesByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoteByID'
type MockListNotesByIDRepository_ListNotesByID_Call struct {
	*mock.Call
}

// ListNotesByID is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - notesID []string
func (_e *MockListNotesByIDRepository_Expecter) ListNotesByID(ctx interface{}, authorID interface{}, notesID interface{}) *MockListNotesByIDRepository_ListNotesByID_Call {
	return &MockListNotesByIDRepository_ListNotesByID_Call{Call: _e.mock.On("GetNoteByID", ctx, authorID, notesID)}
}

func (_c *MockListNotesByIDRepository_ListNotesByID_Call) Run(run func(ctx context.Context, authorID string, notesID []string)) *MockListNotesByIDRepository_ListNotesByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockListNotesByIDRepository_ListNotesByID_Call) Return(_a0 []*entities.Note, _a1 error) *MockListNotesByIDRepository_ListNotesByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListNotesByIDRepository_ListNotesByID_Call) RunAndReturn(run func(context.Context, string, []string) ([]*entities.Note, error)) *MockListNotesByIDRepository_ListNotesByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListNotesByIDRepository creates a new instance of MockListNotesByIDRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListNotesByIDRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListNotesByIDRepository {
	mock := &MockListNotesByIDRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
