// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-notes/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGetNoteByIDRepository is an autogenerated mock type for the GetNoteByIDRepository type
type MockGetNoteByIDRepository struct {
	mock.Mock
}

type MockGetNoteByIDRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetNoteByIDRepository) EXPECT() *MockGetNoteByIDRepository_Expecter {
	return &MockGetNoteByIDRepository_Expecter{mock: &_m.Mock}
}

// GetNoteByID provides a mock function with given fields: ctx, authorID, noteID
func (_m *MockGetNoteByIDRepository) GetNoteByID(ctx context.Context, authorID string, noteID uuid.UUID) (*entities.Note, error) {
	ret := _m.Called(ctx, authorID, noteID)

	if len(ret) == 0 {
		panic("no return value specified for GetNoteByID")
	}

	var r0 *entities.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*entities.Note, error)); ok {
		return rf(ctx, authorID, noteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *entities.Note); ok {
		r0 = rf(ctx, authorID, noteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, authorID, noteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetNoteByIDRepository_GetNoteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoteByID'
type MockGetNoteByIDRepository_GetNoteByID_Call struct {
	*mock.Call
}

// GetNoteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - noteID uuid.UUID
func (_e *MockGetNoteByIDRepository_Expecter) GetNoteByID(ctx interface{}, authorID interface{}, noteID interface{}) *MockGetNoteByIDRepository_GetNoteByID_Call {
	return &MockGetNoteByIDRepository_GetNoteByID_Call{Call: _e.mock.On("GetNoteByID", ctx, authorID, noteID)}
}

func (_c *MockGetNoteByIDRepository_GetNoteByID_Call) Run(run func(ctx context.Context, authorID string, noteID uuid.UUID)) *MockGetNoteByIDRepository_GetNoteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGetNoteByIDRepository_GetNoteByID_Call) Return(_a0 *entities.Note, _a1 error) *MockGetNoteByIDRepository_GetNoteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetNoteByIDRepository_GetNoteByID_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*entities.Note, error)) *MockGetNoteByIDRepository_GetNoteByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetNoteByIDRepository creates a new instance of MockGetNoteByIDRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetNoteByIDRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetNoteByIDRepository {
	mock := &MockGetNoteByIDRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
